### ISSUE TITLE
Chyba Soubory Online (více informací v protokolu)

### ISSUE THREAD

**Issue by martinpetracek** [kodi-czsk/plugin.video.online-files#24]
Po aktualizaci (Commits on Mar 20, 2018) přestal modul fungovat (předtím ok). Vůbec nenaběhne.

něco z logu:

ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndentationError'>
                                            Error Contents: ('unindent does not match any outer indentation level', ('C:\\Users\\marti\\AppData\\Roaming\\Kodi\\addons\\plugin.video.online-files\\resources\\lib\\hellspy.py', 115, 39, '            \tself._filter(result,item)\n'))
                                            Traceback (most recent call last):
                                              File "C:\Users\marti\AppData\Roaming\Kodi\addons\plugin.video.online-files\default.py", line 36, in <module>
                                                import bezvadata,hellspy,ulozto,fastshare,webshare
                                            IndentationError: ('unindent does not match any outer indentation level', ('C:\\Users\\marti\\AppData\\Roaming\\Kodi\\addons\\plugin.video.online-files\\resources\\lib\\hellspy.py', 115, 39, '            \tself._filter(result,item)\n'))
                                            -->End of Python script error report<--

**Comment by czPechy** [comment]
Díky za nahlášení. 
Nějak se mi to domíchalo, mám totiž tenhle plugin ve dvou samostatných verzích (jako soubory online a jelikož nic jiného nepoužívám tam mám ještě samostatnej Hellspy) a nějak jsem to blbě pospojoval. 
Pull request s opravou je tam.

**Comment by martinpetracek** [comment]
To byla rychlost 👍  (oprava funguje)
