### ISSUE TITLE
Podobne hledani

### ISSUE THREAD

**Issue by kadledav** [kodi-czsk/plugin.video.online-files#7]
Ahoj, kdyz hledam epizodu serialu ve tvaru 'nazev serialu s01e01' a pak chci videt dalsi dil, musim znova psat cely text  'nazev serialu s01e02' . Lze upravit doplnek nebo nejak nakonfigurovat Kodi,  abych mohl vyuzit historie? Psani znova celeho textu je na ovladaci peklo, hlavne kdyz vim ze potrebuji zmenit pouze jedno pismenko.

Myslim ze by v pohode stacilo k zaznamu v historii pridat do kontextove nabidky volbu typu: 'hledat podobne' a to by otevrelo klasicky search dialog s predvyplnenym vstupem.

Mimochodem soubory online je super doplnek, diky za jeho vyvoj a udrzbu

**Comment by lzoubek** [comment]
Hotovo, tato feature je nyni dostupna pro vsechny pluginy vyuzivajici spolecny modul `stream.resolver`
